const path = require('path');
const fs = require('fs-extra');

// Image processing library - Sharp for fast processing on VPS/Desktop
let sharp = null;
try {
    sharp = require('sharp');
    console.log('✅ Sharp loaded - Custom icon support enabled');
} catch (e) {
    console.warn('⚠️ Sharp not available. Custom icons disabled. Run: npm install sharp');
}

/**
 * Generate Android project from template
 * @param {string} outputDir - Output directory
 * @param {Object} config - User configuration
 */
async function generateProject(outputDir, config) {
    const templateDir = path.join(__dirname, '..', '..', 'android-template');

    // Check if template exists
    if (!await fs.pathExists(templateDir)) {
        throw new Error('Template Android tidak ditemukan. Jalankan setup terlebih dahulu.');
    }

    console.log(`[Project] Copying template to ${outputDir}`);
    await fs.copy(templateDir, outputDir);

    // Generate unique package name
    const packageName = generatePackageName(config.appName);
    console.log(`[Project] Package name: ${packageName}`);

    // Update configurations
    console.log('[Project] Updating app name...');
    await updateAppName(outputDir, config.appName);
    
    console.log('[Project] Updating WebView URL...');
    await updateWebViewUrl(outputDir, config.url);
    
    console.log('[Project] Updating theme color...');
    await updateThemeColor(outputDir, config.themeColor);

    // Update icon if provided
    if (config.iconPath && await fs.pathExists(config.iconPath)) {
        console.log('[Project] Updating app icon...');
        await updateAppIcon(outputDir, config.iconPath);
    } else {
        console.log('[Project] Using default icon');
    }

    // Update package name in project files
    console.log('[Project] Updating package name...');
    await updatePackageName(outputDir, packageName);

    // Create local.properties with SDK path
    console.log('[Project] Creating local.properties...');
    await createLocalProperties(outputDir);
    
    // Create keystore.properties for signing (if needed)
    await createKeystoreProperties(outputDir);
    
    console.log('[Project] ✅ Project generation complete');
}

/**
 * Create local.properties with SDK path
 */
async function createLocalProperties(projectDir) {
    const localPropsPath = path.join(projectDir, 'local.properties');

    const possiblePaths = [
        '/opt/android-sdk',
        '/usr/lib/android-sdk',
        process.env.HOME + '/Android/Sdk',
        process.env.HOME + '/android-sdk',
        'C:\\Users\\' + (process.env.USERNAME || 'User') + '\\AppData\\Local\\Android\\Sdk',
    ];

    let sdkPath = null;

    for (const p of possiblePaths) {
        if (await fs.pathExists(p)) {
            sdkPath = p;
            console.log(`[Project] Found SDK at: ${sdkPath}`);
            break;
        }
    }

    if (!sdkPath) {
        const envPath = process.env.ANDROID_HOME || process.env.ANDROID_SDK_ROOT;
        if (envPath && await fs.pathExists(envPath)) {
            sdkPath = envPath;
            console.log(`[Project] Using SDK from env: ${sdkPath}`);
        }
    }

    if (sdkPath) {
        const normalizedPath = sdkPath.replace(/\\/g, '/');
        const content = `# Auto-generated by Web4APK\nsdk.dir=${normalizedPath}\n`;
        await fs.writeFile(localPropsPath, content);
        console.log(`[Project] ✅ Created local.properties with SDK path: ${sdkPath}`);
    } else {
        console.warn('[Project] ⚠️ Warning: Could not find Android SDK path');
    }
}

/**
 * Create keystore.properties for APK signing
 */
async function createKeystoreProperties(projectDir) {
    const keystorePropsPath = path.join(projectDir, 'keystore.properties');
    
    // Check if we have keystore configured
    const keystorePath = process.env.KEYSTORE_PATH;
    const keystorePassword = process.env.KEYSTORE_PASSWORD;
    const keyAlias = process.env.KEY_ALIAS;
    const keyPassword = process.env.KEY_PASSWORD;
    
    if (keystorePath && keystorePassword && keyAlias) {
        const content = `# Auto-generated by Web4APK
storeFile=${keystorePath}
storePassword=${keystorePassword}
keyAlias=${keyAlias}
keyPassword=${keyPassword || keystorePassword}
`;
        await fs.writeFile(keystorePropsPath, content);
        console.log('[Project] ✅ Created keystore.properties for signing');
    } else {
        console.log('[Project] ℹ️ No keystore configured, using debug signing');
    }
}

/**
 * Update app name in strings.xml
 */
async function updateAppName(projectDir, appName) {
    const stringsPath = path.join(projectDir, 'app', 'src', 'main', 'res', 'values', 'strings.xml');

    let content = await fs.readFile(stringsPath, 'utf8');
    content = content.replace(
        /<string name="app_name">.*<\/string>/,
        `<string name="app_name">${escapeXml(appName)}</string>`
    );
    await fs.writeFile(stringsPath, content);
    console.log(`[Project] App name updated to: ${appName}`);
}

/**
 * Update WebView URL in MainActivity
 */
async function updateWebViewUrl(projectDir, url) {
    const mainActivityPath = path.join(projectDir, 'app', 'src', 'main', 'java', 'com', 'web4apk', 'app', 'MainActivity.java');

    // Simple encoding: reverse string then Base64
    const reversed = url.split('').reverse().join('');
    const encoded = Buffer.from(reversed, 'utf8').toString('base64');

    let content = await fs.readFile(mainActivityPath, 'utf8');

    content = content.replace(
        /private static final String ENCODED_URL = "[^"]*";/,
        `private static final String ENCODED_URL = "${encoded}";`
    );

    content = content.replace(
        /private static final String FALLBACK_URL = "[^"]*";/,
        `private static final String FALLBACK_URL = "${url}";`
    );

    await fs.writeFile(mainActivityPath, content);
    console.log(`[Project] WebView URL updated: ${url}`);
}

/**
 * Update theme color in colors.xml
 */
async function updateThemeColor(projectDir, themeColor) {
    const colorsPath = path.join(projectDir, 'app', 'src', 'main', 'res', 'values', 'colors.xml');

    const darkColor = darkenColor(themeColor, 20);
    const lightColor = lightenColor(themeColor, 30);

    let content = await fs.readFile(colorsPath, 'utf8');
    content = content.replace(
        /<color name="colorPrimary">.*<\/color>/,
        `<color name="colorPrimary">${themeColor}</color>`
    );
    content = content.replace(
        /<color name="colorPrimaryDark">.*<\/color>/,
        `<color name="colorPrimaryDark">${darkColor}</color>`
    );
    content = content.replace(
        /<color name="colorAccent">.*<\/color>/,
        `<color name="colorAccent">${themeColor}</color>`
    );
    content = content.replace(
        /<color name="colorPrimaryLight">.*<\/color>/,
        `<color name="colorPrimaryLight">${lightColor}</color>`
    );
    await fs.writeFile(colorsPath, content);
    console.log(`[Project] Theme color updated to: ${themeColor}`);
}

/**
 * Update app icon with user's image
 */
async function updateAppIcon(projectDir, iconPath) {
    if (!sharp) {
        console.warn('⚠️ Sharp not available, using default icon');
        return;
    }

    try {
        const sizes = [
            { name: 'mipmap-mdpi', size: 48 },
            { name: 'mipmap-hdpi', size: 72 },
            { name: 'mipmap-xhdpi', size: 96 },
            { name: 'mipmap-xxhdpi', size: 144 },
            { name: 'mipmap-xxxhdpi', size: 192 }
        ];

        // Read image metadata
        const metadata = await sharp(iconPath).metadata();
        const isSquare = metadata.width === metadata.height;
        const fitOption = isSquare ? 'cover' : 'contain';
        
        console.log(`[Project] Icon dimensions: ${metadata.width}x${metadata.height}, ${isSquare ? 'square' : 'non-square'}`);

        for (const { name, size } of sizes) {
            const outputPath = path.join(projectDir, 'app', 'src', 'main', 'res', name, 'ic_launcher.png');
            const roundOutputPath = path.join(projectDir, 'app', 'src', 'main', 'res', name, 'ic_launcher_round.png');

            await fs.ensureDir(path.dirname(outputPath));

            // Process for square icon
            await sharp(iconPath)
                .resize(size, size, { 
                    fit: fitOption,
                    background: { r: 255, g: 255, b: 255, alpha: 1 }
                })
                .png()
                .toFile(outputPath);

            // Process for round icon (with circular mask)
            const roundBuffer = await sharp(iconPath)
                .resize(size, size, { fit: 'cover' })
                .png()
                .toBuffer();
            
            // Create circular icon
            const { createRoundIcon } = require('./iconUtils');
            await createRoundIcon(roundBuffer, roundOutputPath, size);
            
            console.log(`[Project] Generated icon: ${name} (${size}x${size})`);
        }

        console.log('✅ Custom icon applied successfully');
    } catch (error) {
        console.warn('⚠️ Custom icon processing failed, using default icon:', error.message);
    }
}

/**
 * Update package name
 */
async function updatePackageName(projectDir, newPackageName) {
    const buildGradlePath = path.join(projectDir, 'app', 'build.gradle');
    let buildGradle = await fs.readFile(buildGradlePath, 'utf8');

    buildGradle = buildGradle.replace(
        /applicationId ".*"/,
        `applicationId "${newPackageName}"`
    );

    buildGradle = buildGradle.replace(
        /namespace '.*'/,
        `namespace '${newPackageName}'`
    );

    await fs.writeFile(buildGradlePath, buildGradle);
    console.log(`[Project] Updated build.gradle with package: ${newPackageName}`);

    const javaDir = path.join(projectDir, 'app', 'src', 'main', 'java', 'com', 'web4apk', 'app');
    
    if (await fs.pathExists(javaDir)) {
        const javaFiles = await fs.readdir(javaDir);
        
        const newPackageDir = path.join(projectDir, 'app', 'src', 'main', 'java', ...newPackageName.split('.'));
        await fs.ensureDir(newPackageDir);
        
        for (const file of javaFiles) {
            if (file.endsWith('.java')) {
                const oldPath = path.join(javaDir, file);
                const newPath = path.join(newPackageDir, file);
                
                let content = await fs.readFile(oldPath, 'utf8');
                content = content.replace(
                    /package com\.web4apk\.app;/,
                    `package ${newPackageName};`
                );
                await fs.writeFile(newPath, content);
                console.log(`[Project] Updated Java file: ${file}`);
            }
        }
        
        const oldPackageDir = path.join(projectDir, 'app', 'src', 'main', 'java', 'com', 'web4apk', 'app');
        if (await fs.pathExists(oldPackageDir) && oldPackageDir !== newPackageDir) {
            await fs.remove(oldPackageDir);
            console.log(`[Project] Cleaned up old package directory`);
        }
    }
}

/**
 * Generate unique package name from app name
 */
function generatePackageName(appName) {
    const sanitized = appName
        .toLowerCase()
        .replace(/[^a-z0-9]/g, '')
        .substring(0, 20);

    const timestamp = Date.now().toString(36);
    const random = Math.random().toString(36).substring(2, 6);
    return `com.web4apk.${sanitized || 'app'}_${timestamp}_${random}`;
}

/**
 * Escape XML special characters
 */
function escapeXml(str) {
    if (!str) return '';
    return str
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&apos;');
}

/**
 * Darken a hex color
 */
function darkenColor(hex, percent) {
    const num = parseInt(hex.replace('#', ''), 16);
    const amt = Math.round(2.55 * percent);
    const R = Math.max((num >> 16) - amt, 0);
    const G = Math.max((num >> 8 & 0x00FF) - amt, 0);
    const B = Math.max((num & 0x0000FF) - amt, 0);
    return '#' + (0x1000000 + R * 0x10000 + G * 0x100 + B).toString(16).slice(1);
}

/**
 * Lighten a hex color
 */
function lightenColor(hex, percent) {
    const num = parseInt(hex.replace('#', ''), 16);
    const amt = Math.round(2.55 * percent);
    const R = Math.min((num >> 16) + amt, 255);
    const G = Math.min((num >> 8 & 0x00FF) + amt, 255);
    const B = Math.min((num & 0x0000FF) + amt, 255);
    return '#' + (0x1000000 + R * 0x10000 + G * 0x100 + B).toString(16).slice(1);
}

module.exports = { generateProject };